from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^account/$',
            views.ManageKursusListView.as_view(),
            name='manage_kursus_list'),
        url(r'^create/$',
            views.KursusCreateView.as_view(),
            name='kursus_create'),
        url(r'^(?P<pk>\d+)/edit/$',
            views.KursusUpdateView.as_view(),
            name='kursus_edit'),
        url(r'^(?P<pk>\d+)/delete/$',
            views.KursusDeleteView.as_view(),
            name='kursus_delete'),
        url(r'^(?P<pk>\d+)/module/$',
            views.KursusModulUpdateView.as_view(),
            name='kursus_modul_update'),
        url(r'^module/(?P<modul_id>\d+)/content/(?P<model_name>\w+)/create/$',
            views.KontenCreateUpdateView.as_view(),
            name='modul_konten_create'),
        url(r'^module/(?P<modul_id>\d+)/content/(?P<model_name>\w+)/(?P<id>\d+)/$',
            views.KontenCreateUpdateView.as_view(),
            name='modul_konten_update'),
        url(r'^content/(?P<id>\d+)/delete/$',
            views.KontenDeleteView.as_view(),
            name='modul_konten_delete'),
        url(r'^module/(?P<modul_id>\d+)/$',
            views.ModulKontenListView.as_view(),
            name='modul_konten_list'),
        ]